using M2.NSudo;

new NSudoInstance().CreateProcess(
    NSUDO_USER_MODE_TYPE.TRUSTED_INSTALLER,
    NSUDO_PRIVILEGES_MODE_TYPE.ENABLE_ALL_PRIVILEGES,
    NSUDO_MANDATORY_LABEL_TYPE.SYSTEM,
    NSUDO_PROCESS_PRIORITY_CLASS_TYPE.NORMAL,
    NSUDO_SHOW_WINDOW_MODE_TYPE.DEFAULT,
    0,
    true,
    "BetterWin11 Builder.exe " + args[0],
    null);